Update build - don't cp directory, just bits we need (#122)
## Summary:

When I cut the last release, it [hit an error during the release](https://github.com/Khan/actions/actions/runs/19350654496/job/55361517538). It looks like it was trying to copy a file/dir within `node_modules` to the dist/ folder for a package. This shouldn't be needed as we bundle our JS actions into a single `dist/index.js` file which has no external dependencies. 

So, I've re-worked the build system a little bit. We copy the `action.yml`, `package.json` (if it exists), and then build the `index.js` to `dist/index.js` using [`ncc`](https://github.com/vercel/ncc) (if the source file exists). 

This simplifies our build setup and will clean up what we publish (right now we publish the tags with a bunch of source artifacts that aren't needed). 


```
node:fs:3035
  binding.copyFile(
          ^
Error: EISDIR: illegal operation on a directory, copyfile 'actions/check-for-changeset/node_modules/filter-files' -> 'actions/check-for-changeset/dist/node_modules/filter-files'
    at Object.copyFileSync (node:fs:3035:11)
    at copyDir (file:///home/runner/work/actions/actions/utils/build.mjs:24:16)
    at copyDir (file:///home/runner/work/actions/actions/utils/build.mjs:22:13)
    at buildPackage (file:///home/runner/work/actions/actions/utils/build.mjs:73:5)
    at file:///home/runner/work/actions/actions/utils/publish.mjs:119:30
    at Array.forEach (<anonymous>)
    at publishAsNeeded (file:///home/runner/work/actions/actions/utils/publish.mjs:113:18)
    at file:///home/runner/work/actions/actions/utils/run-publish.mjs:11:1
    at ModuleJob.run (node:internal/modules/esm/module_job:325:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'copyfile',
  path: 'actions/check-for-changeset/node_modules/filter-files',
  dest: 'actions/check-for-changeset/dist/node_modules/filter-files'
}
Node.js v20.19.5
```

Issue: LEMS-3681

## Test plan:

I tested by running a publish in a dry-run: 

<details>
  <summary>Dry run output</summary>

```
Publishing (dry run)...
Processing apply-terraform-plan...
  Version apply-terraform-plan-v2.1.0 already exists. Nothing to do.

Processing check-for-changeset...
  Copying actions/check-for-changeset/package.json to actions/check-for-changeset/dist/package.json
  Copying actions/check-for-changeset/CHANGELOG.md to actions/check-for-changeset/dist/CHANGELOG.md
  Copying actions/check-for-changeset/package.json to actions/check-for-changeset/dist/package.json
  Processing action.yml for check-for-changeset
    Processing dependency: get-changed-files
      Replacing with: Khan/actions@get-changed-files-v2.1.1
    Processing dependency: filter-files
      Replacing with: Khan/actions@filter-files-v2.1.0
  Building actions/check-for-changeset/index.js
  Publishing check-for-changeset-v1.0.3 in actions/check-for-changeset/dist
  >> git init .
  >> git add .
  >> git config user.email "khan-actions-bot@khanacademy.org"
  >> git config user.name "Khan Actions Bot"
  >> git commit -m publish
  >> git remote add origin git@github.com:Khan/actions.git
  >> git fetch origin --tags
  >> git tag check-for-changeset-v1.0.3
  >> git tag -f check-for-changeset-v1
🏁  Finished publishing check-for-changeset-v1.0.3

Processing cypress-install...
  Version cypress-install-v0.0.1 already exists. Nothing to do.

Processing filter-files...
  Version filter-files-v2.1.0 already exists. Nothing to do.

Processing full-or-limited...
  Version full-or-limited-v0.0.2 already exists. Nothing to do.

Processing generate-terraform-plan...
  Version generate-terraform-plan-v2.2.1 already exists. Nothing to do.

Processing gerald-pr...
  Copying actions/gerald-pr/package.json to actions/gerald-pr/dist/package.json
  Copying actions/gerald-pr/CHANGELOG.md to actions/gerald-pr/dist/CHANGELOG.md
  Copying actions/gerald-pr/package.json to actions/gerald-pr/dist/package.json
  Processing action.yml for gerald-pr
    Processing dependency: get-changed-files
      Replacing with: Khan/actions@get-changed-files-v2.1.1
  Publishing gerald-pr-v3.1.4 in actions/gerald-pr/dist
  >> git init .
  >> git add .
  >> git config user.email "khan-actions-bot@khanacademy.org"
  >> git config user.name "Khan Actions Bot"
  >> git commit -m publish
  >> git remote add origin git@github.com:Khan/actions.git
  >> git fetch origin --tags
  >> git tag gerald-pr-v3.1.4
  >> git tag -f gerald-pr-v3
🏁  Finished publishing gerald-pr-v3.1.4

Processing get-changed-files...
  Copying actions/get-changed-files/package.json to actions/get-changed-files/dist/package.json
  Copying actions/get-changed-files/CHANGELOG.md to actions/get-changed-files/dist/CHANGELOG.md
  Copying actions/get-changed-files/package.json to actions/get-changed-files/dist/package.json
  Processing action.yml for get-changed-files
  Building actions/get-changed-files/index.js
  Publishing get-changed-files-v2.1.1 in actions/get-changed-files/dist
  >> git init .
  >> git add .
  >> git config user.email "khan-actions-bot@khanacademy.org"
  >> git config user.name "Khan Actions Bot"
  >> git commit -m publish
  >> git remote add origin git@github.com:Khan/actions.git
  >> git fetch origin --tags
  >> git tag get-changed-files-v2.1.1
  >> git tag -f get-changed-files-v2
🏁  Finished publishing get-changed-files-v2.1.1

Processing json-args...
  Version json-args-v1.0.0 already exists. Nothing to do.

Processing shared-node-cache...
  Version shared-node-cache-v3.0.0 already exists. Nothing to do.
```

</details>

<details>
<summary><code>dist/</code> folder contents</summary>

```
actions/check-for-changeset/dist
actions/check-for-changeset/dist/sourcemap-register.js
actions/check-for-changeset/dist/index.js
actions/check-for-changeset/dist/package.json
actions/check-for-changeset/dist/index.js.map
actions/check-for-changeset/dist/action.yml

actions/filter-files/dist
actions/filter-files/dist/CHANGELOG.md
actions/filter-files/dist/sourcemap-register.js
actions/filter-files/dist/index.js
actions/filter-files/dist/package.json
actions/filter-files/dist/index.js.map
actions/filter-files/dist/action.yml

actions/full-or-limited/dist
actions/full-or-limited/dist/CHANGELOG.md
actions/full-or-limited/dist/package.json
actions/full-or-limited/dist/action.yml

actions/gerald-pr/dist
actions/gerald-pr/dist/package.json
actions/gerald-pr/dist/action.yml

actions/get-changed-files/dist
actions/get-changed-files/dist/sourcemap-register.js
actions/get-changed-files/dist/index.js
actions/get-changed-files/dist/package.json
actions/get-changed-files/dist/index.js.map
actions/get-changed-files/dist/action.yml

actions/json-args/dist
actions/json-args/dist/CHANGELOG.md
actions/json-args/dist/package.json
actions/json-args/dist/action.yml

actions/shared-node-cache/dist
actions/shared-node-cache/dist/CHANGELOG.md
actions/shared-node-cache/dist/package.json
actions/shared-node-cache/dist/action.yml
```

</summary>

Author: jeremywiebe

Reviewers: jeremywiebe, somewhatabstract, jaredly, kevinb-khan

Required Reviewers:

Approved By: somewhatabstract, jaredly

Checks: ✅ 3 checks were successful

Pull Request URL: https://github.com/Khan/actions/pull/122