Fix building packages (#142)
## Summary:
This PR addresses the following issue I ran into with https://github.com/Khan/actions/actions/runs/22865811130/job/66332195947:

```
Error: [tsl] ERROR
      TS5096: Option 'allowImportingTsExtensions' can only be used when either 'noEmit' or 'emitDeclarationOnly' is set.
    at /home/runner/work/actions/actions/node_modules/.pnpm/@vercel+ncc@0.36.1/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1870077
    at /home/runner/work/actions/actions/node_modules/.pnpm/@vercel+ncc@0.36.1/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:383620
    at _done (eval at create (/home/runner/work/actions/actions/node_modules/.pnpm/@vercel+ncc@0.36.1/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:9:1)
    at eval (eval at create (/home/runner/work/actions/actions/node_modules/.pnpm/@vercel+ncc@0.36.1/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:34:22)
Error: Command failed: pnpm ncc build actions/filter-files/index.ts -o actions/filter-files/dist --source-map
Error: [tsl] ERROR
      TS5096: Option 'allowImportingTsExtensions' can only be used when either 'noEmit' or 'emitDeclarationOnly' is set.
```

I added a `--force` flag in order to get run-publish.ts to run the build even when there were no new tags to publish.

Issue: None

## Test plan:
- `node -r @swc-node/register ./utils/run-publish.ts --dry-run --force`

```
$ node -r @swc-node/register ./utils/run-publish.ts --dry-run --force
Publishing (dry run)...
From .
 * branch            main       -> FETCH_HEAD
Processing apply-terraform-plan...
  Copying actions/apply-terraform-plan/package.json to actions/apply-terraform-plan/dist/package.json
  Copying actions/apply-terraform-plan/CHANGELOG.md to actions/apply-terraform-plan/dist/CHANGELOG.md
  Processing action.yml for apply-terraform-plan
  Publishing apply-terraform-plan-v2.2.1 in actions/apply-terraform-plan/dist
  >> git init .
  >> git add .
  >> git config user.email "khan-actions-bot@khanacademy.org"
  >> git config user.name "Khan Actions Bot"
  >> git commit -m publish
  >> git remote add origin git@github.com:Khan/actions.git
  >> git fetch origin --tags
  >> git tag apply-terraform-plan-v2.2.1
  >> git push origin --tags
🏁  Finished publishing apply-terraform-plan-v2.2.1

...

Processing filter-files...
  Copying actions/filter-files/package.json to actions/filter-files/dist/package.json
  Copying actions/filter-files/CHANGELOG.md to actions/filter-files/dist/CHANGELOG.md
  Processing action.yml for filter-files
  Building actions/filter-files/index.ts
  Publishing filter-files-v2.1.1 in actions/filter-files/dist
  >> git init .
  >> git add .
  >> git config user.email "khan-actions-bot@khanacademy.org"
  >> git config user.name "Khan Actions Bot"
  >> git commit -m publish
  >> git remote add origin git@github.com:Khan/actions.git
  >> git fetch origin --tags
  >> git tag filter-files-v2.1.1
  >> git push origin --tags
🏁  Finished publishing filter-files-v2.1.1

...
```

Author: kevinb-khan

Reviewers: jeresig, jaredly

Required Reviewers:

Approved By: jeresig

Checks: ✅ 3 checks were successful

Pull Request URL: https://github.com/Khan/actions/pull/142